[package]
name = "weak-table"
version = "0.2.4-alpha.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "Weak hash maps and sets"
repository = "https://github.com/tov/weak-table-rs"
readme = "README.md"
license = "MIT"
keywords = ["containers", "Rc", "Arc", "weak"]

[dependencies]

[dev-dependencies]
quickcheck = "0.6"

