[package]
name = "weak-table"
version = "0.3.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "Weak hash maps and sets"
repository = "https://github.com/tov/weak-table-rs"
readme = "README.md"
license = "MIT"
keywords = ["containers", "Rc", "Arc", "weak"]
edition = "2018"

[dependencies]

[dev-dependencies]
quickcheck = "0.9"
rand = "0.7.2"

